# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'age_range',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'audience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('vkid', models.IntegerField(primary_key=True, serialize=False)),
                ('deactivated', models.BooleanField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('members', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField()),
                ('verified', models.NullBooleanField()),
                ('site', models.TextField()),
                ('age_limit', models.SmallIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('audience_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'community',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'community_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('vkid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sex_vkid', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Woman'), (2, 'Man')])),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
    ]
